import { IActionMap, InputBinding, InputListener } from ".";

export class KeyBindSystem {
    public static readonly bindings: Map<string, InputBinding> = new Map([
        ["0", new InputBinding("0", { light: "/Icons/1.1/Light/0.svg", dark: "/Icons/1.1/Dark/0.svg" },  InputListener.Mouse)],
        ["1", new InputBinding("1", { light: "/Icons/1.1/Light/1.svg", dark: "/Icons/1.1/Dark/1.svg" },  InputListener.Mouse)],
        ["2", new InputBinding("2", { light: "/Icons/1.1/Light/2.svg", dark: "/Icons/1.1/Dark/2.svg" },  InputListener.Mouse)],
        ["3", new InputBinding("3", { light: "/Icons/1.1/Light/3.svg", dark: "/Icons/1.1/Dark/3.svg" },  InputListener.Mouse)],
        ["4", new InputBinding("4", { light: "/Icons/1.1/Light/4.svg", dark: "/Icons/1.1/Dark/4.svg" },  InputListener.Mouse)],
        ["Escape", new InputBinding("Escape", { light: "/Icons/1.1/Light/Escape.svg", dark: "/Icons/1.1/Dark/Escape.svg" },  InputListener.Keyboard)],
        ["F1", new InputBinding("F1", { light: "/Icons/1.1/Light/F1.svg", dark: "/Icons/1.1/Dark/F1.svg" },  InputListener.Keyboard)],
        ["F2", new InputBinding("F2", { light: "/Icons/1.1/Light/F2.svg", dark: "/Icons/1.1/Dark/F2.svg" },  InputListener.Keyboard)],
        ["F4", new InputBinding("F4", { light: "/Icons/1.1/Light/F4.svg", dark: "/Icons/1.1/Dark/F4.svg" },  InputListener.Keyboard)],
        ["F5", new InputBinding("F5", { light: "/Icons/1.1/Light/F5.svg", dark: "/Icons/1.1/Dark/F5.svg" },  InputListener.Keyboard)],
        ["F6", new InputBinding("F6", { light: "/Icons/1.1/Light/F6.svg", dark: "/Icons/1.1/Dark/F6.svg" },  InputListener.Keyboard)],
        ["F7", new InputBinding("F7", { light: "/Icons/1.1/Light/F7.svg", dark: "/Icons/1.1/Dark/F7.svg" },  InputListener.Keyboard)],
        ["F8", new InputBinding("F8", { light: "/Icons/1.1/Light/F8.svg", dark: "/Icons/1.1/Dark/F8.svg" },  InputListener.Keyboard)],
        ["F9", new InputBinding("F9", { light: "/Icons/1.1/Light/F9.svg", dark: "/Icons/1.1/Dark/F9.svg" },  InputListener.Keyboard)],
        ["F10", new InputBinding("F10", { light: "/Icons/1.1/Light/F10.svg", dark: "/Icons/1.1/Dark/F10.svg" },  InputListener.Keyboard)],
        ["F12", new InputBinding("F12", { light: "/Icons/1.1/Light/F12.svg", dark: "/Icons/1.1/Dark/F12.svg" },  InputListener.Keyboard)],
        ["Backquote", new InputBinding("Backquote", { light: "/Icons/1.1/Light/Backquote.svg", dark: "/Icons/1.1/Dark/Backquote.svg" },  InputListener.Keyboard)],
        ["Digit1", new InputBinding("Digit1", { light: "/Icons/1.1/Light/Digit1.svg", dark: "/Icons/1.1/Dark/Digit1.svg" },  InputListener.Keyboard)],
        ["Digit2", new InputBinding("Digit2", { light: "/Icons/1.1/Light/Digit2.svg", dark: "/Icons/1.1/Dark/Digit2.svg" },  InputListener.Keyboard)],
        ["Digit3", new InputBinding("Digit3", { light: "/Icons/1.1/Light/Digit3.svg", dark: "/Icons/1.1/Dark/Digit3.svg" },  InputListener.Keyboard)],
        ["Digit4", new InputBinding("Digit4", { light: "/Icons/1.1/Light/Digit4.svg", dark: "/Icons/1.1/Dark/Digit4.svg" },  InputListener.Keyboard)],
        ["Digit5", new InputBinding("Digit5", { light: "/Icons/1.1/Light/Digit5.svg", dark: "/Icons/1.1/Dark/Digit5.svg" },  InputListener.Keyboard)],
        ["Digit6", new InputBinding("Digit6", { light: "/Icons/1.1/Light/Digit6.svg", dark: "/Icons/1.1/Dark/Digit6.svg" },  InputListener.Keyboard)],
        ["Digit7", new InputBinding("Digit7", { light: "/Icons/1.1/Light/Digit7.svg", dark: "/Icons/1.1/Dark/Digit7.svg" },  InputListener.Keyboard)],
        ["Digit8", new InputBinding("Digit8", { light: "/Icons/1.1/Light/Digit8.svg", dark: "/Icons/1.1/Dark/Digit8.svg" },  InputListener.Keyboard)],
        ["Digit9", new InputBinding("Digit9", { light: "/Icons/1.1/Light/Digit9.svg", dark: "/Icons/1.1/Dark/Digit9.svg" },  InputListener.Keyboard)],
        ["Digit0", new InputBinding("Digit0", { light: "/Icons/1.1/Light/Digit0.svg", dark: "/Icons/1.1/Dark/Digit0.svg" },  InputListener.Keyboard)],
        ["Minus", new InputBinding("Minus", { light: "/Icons/1.1/Light/Minus.svg", dark: "/Icons/1.1/Dark/Minus.svg" },  InputListener.Keyboard)],
        ["Equal", new InputBinding("Equal", { light: "/Icons/1.1/Light/Equal.svg", dark: "/Icons/1.1/Dark/Equal.svg" },  InputListener.Keyboard)],
        ["Backspace", new InputBinding("Backspace", { light: "/Icons/1.1/Light/Backspace.svg", dark: "/Icons/1.1/Dark/Backspace.svg" },  InputListener.Keyboard)],
        ["Tab", new InputBinding("Tab", { light: "/Icons/1.1/Light/Tab.svg", dark: "/Icons/1.1/Dark/Tab.svg" },  InputListener.Keyboard)],
        ["KeyQ", new InputBinding("KeyQ", { light: "/Icons/1.1/Light/KeyQ.svg", dark: "/Icons/1.1/Dark/KeyQ.svg" },  InputListener.Keyboard)],
        ["KeyW", new InputBinding("KeyW", { light: "/Icons/1.1/Light/KeyW.svg", dark: "/Icons/1.1/Dark/KeyW.svg" },  InputListener.Keyboard)],
        ["KeyE", new InputBinding("KeyE", { light: "/Icons/1.1/Light/KeyE.svg", dark: "/Icons/1.1/Dark/KeyE.svg" },  InputListener.Keyboard)],
        ["KeyR", new InputBinding("KeyR", { light: "/Icons/1.1/Light/KeyR.svg", dark: "/Icons/1.1/Dark/KeyR.svg" },  InputListener.Keyboard)],
        ["KeyT", new InputBinding("KeyT", { light: "/Icons/1.1/Light/KeyT.svg", dark: "/Icons/1.1/Dark/KeyT.svg" },  InputListener.Keyboard)],
        ["KeyY", new InputBinding("KeyY", { light: "/Icons/1.1/Light/KeyY.svg", dark: "/Icons/1.1/Dark/KeyY.svg" },  InputListener.Keyboard)],
        ["KeyU", new InputBinding("KeyU", { light: "/Icons/1.1/Light/KeyU.svg", dark: "/Icons/1.1/Dark/KeyU.svg" },  InputListener.Keyboard)],
        ["KeyI", new InputBinding("KeyI", { light: "/Icons/1.1/Light/KeyI.svg", dark: "/Icons/1.1/Dark/KeyI.svg" },  InputListener.Keyboard)],
        ["KeyO", new InputBinding("KeyO", { light: "/Icons/1.1/Light/KeyO.svg", dark: "/Icons/1.1/Dark/KeyO.svg" },  InputListener.Keyboard)],
        ["KeyP", new InputBinding("KeyP", { light: "/Icons/1.1/Light/KeyP.svg", dark: "/Icons/1.1/Dark/KeyP.svg" },  InputListener.Keyboard)],
        ["BracketLeft", new InputBinding("BracketLeft", { light: "/Icons/1.1/Light/BracketLeft.svg", dark: "/Icons/1.1/Dark/BracketLeft.svg" },  InputListener.Keyboard)],
        ["BracketRight", new InputBinding("BracketRight", { light: "/Icons/1.1/Light/BracketRight.svg", dark: "/Icons/1.1/Dark/BracketRight.svg" },  InputListener.Keyboard)],
        ["Backslash", new InputBinding("Backslash", { light: "/Icons/1.1/Light/Backslash.svg", dark: "/Icons/1.1/Dark/Backslash.svg" },  InputListener.Keyboard)],
        ["CapsLock", new InputBinding("CapsLock", { light: "/Icons/1.1/Light/CapsLock.svg", dark: "/Icons/1.1/Dark/CapsLock.svg" },  InputListener.Keyboard)],
        ["KeyA", new InputBinding("KeyA", { light: "/Icons/1.1/Light/KeyA.svg", dark: "/Icons/1.1/Dark/KeyA.svg" },  InputListener.Keyboard)],
        ["KeyS", new InputBinding("KeyS", { light: "/Icons/1.1/Light/KeyS.svg", dark: "/Icons/1.1/Dark/KeyS.svg" },  InputListener.Keyboard)],
        ["KeyD", new InputBinding("KeyD", { light: "/Icons/1.1/Light/KeyD.svg", dark: "/Icons/1.1/Dark/KeyD.svg" },  InputListener.Keyboard)],
        ["KeyF", new InputBinding("KeyF", { light: "/Icons/1.1/Light/KeyF.svg", dark: "/Icons/1.1/Dark/KeyF.svg" },  InputListener.Keyboard)],
        ["KeyG", new InputBinding("KeyG", { light: "/Icons/1.1/Light/KeyG.svg", dark: "/Icons/1.1/Dark/KeyG.svg" },  InputListener.Keyboard)],
        ["KeyH", new InputBinding("KeyH", { light: "/Icons/1.1/Light/KeyH.svg", dark: "/Icons/1.1/Dark/KeyH.svg" },  InputListener.Keyboard)],
        ["KeyJ", new InputBinding("KeyJ", { light: "/Icons/1.1/Light/KeyJ.svg", dark: "/Icons/1.1/Dark/KeyJ.svg" },  InputListener.Keyboard)],
        ["KeyK", new InputBinding("KeyK", { light: "/Icons/1.1/Light/KeyK.svg", dark: "/Icons/1.1/Dark/KeyK.svg" },  InputListener.Keyboard)],
        ["KeyL", new InputBinding("KeyL", { light: "/Icons/1.1/Light/KeyL.svg", dark: "/Icons/1.1/Dark/KeyL.svg" },  InputListener.Keyboard)],
        ["Semicolon", new InputBinding("Semicolon", { light: "/Icons/1.1/Light/Semicolon.svg", dark: "/Icons/1.1/Dark/Semicolon.svg" },  InputListener.Keyboard)],
        ["Quote", new InputBinding("Quote", { light: "/Icons/1.1/Light/Quote.svg", dark: "/Icons/1.1/Dark/Quote.svg" },  InputListener.Keyboard)],
        ["Enter", new InputBinding("Enter", { light: "/Icons/1.1/Light/Enter.svg", dark: "/Icons/1.1/Dark/Enter.svg" },  InputListener.Keyboard)],
        ["ShiftLeft", new InputBinding("ShiftLeft", { light: "/Icons/1.1/Light/ShiftLeft.svg", dark: "/Icons/1.1/Dark/ShiftLeft.svg" },  InputListener.Keyboard)],
        ["KeyZ", new InputBinding("KeyZ", { light: "/Icons/1.1/Light/KeyZ.svg", dark: "/Icons/1.1/Dark/KeyZ.svg" },  InputListener.Keyboard)],
        ["KeyX", new InputBinding("KeyX", { light: "/Icons/1.1/Light/KeyX.svg", dark: "/Icons/1.1/Dark/KeyX.svg" },  InputListener.Keyboard)],
        ["KeyC", new InputBinding("KeyC", { light: "/Icons/1.1/Light/KeyC.svg", dark: "/Icons/1.1/Dark/KeyC.svg" },  InputListener.Keyboard)],
        ["KeyV", new InputBinding("KeyV", { light: "/Icons/1.1/Light/KeyV.svg", dark: "/Icons/1.1/Dark/KeyV.svg" },  InputListener.Keyboard)],
        ["KeyB", new InputBinding("KeyB", { light: "/Icons/1.1/Light/KeyB.svg", dark: "/Icons/1.1/Dark/KeyB.svg" },  InputListener.Keyboard)],
        ["KeyN", new InputBinding("KeyN", { light: "/Icons/1.1/Light/KeyN.svg", dark: "/Icons/1.1/Dark/KeyN.svg" },  InputListener.Keyboard)],
        ["KeyM", new InputBinding("KeyM", { light: "/Icons/1.1/Light/KeyM.svg", dark: "/Icons/1.1/Dark/KeyM.svg" },  InputListener.Keyboard)],
        ["Comma", new InputBinding("Comma", { light: "/Icons/1.1/Light/Comma.svg", dark: "/Icons/1.1/Dark/Comma.svg" },  InputListener.Keyboard)],
        ["Period", new InputBinding("Period", { light: "/Icons/1.1/Light/Period.svg", dark: "/Icons/1.1/Dark/Period.svg" },  InputListener.Keyboard)],
        ["Slash", new InputBinding("Slash", { light: "/Icons/1.1/Light/Slash.svg", dark: "/Icons/1.1/Dark/Slash.svg" },  InputListener.Keyboard)],
        ["ShiftRight", new InputBinding("ShiftRight", { light: "/Icons/1.1/Light/ShiftRight.svg", dark: "/Icons/1.1/Dark/ShiftRight.svg" },  InputListener.Keyboard)],
        ["ControlLeft", new InputBinding("ControlLeft", { light: "/Icons/1.1/Light/ControlLeft.svg", dark: "/Icons/1.1/Dark/ControlLeft.svg" },  InputListener.Keyboard)],
        ["AltLeft", new InputBinding("AltLeft", { light: "/Icons/1.1/Light/AltLeft.svg", dark: "/Icons/1.1/Dark/AltLeft.svg" },  InputListener.Keyboard)],
        ["Space", new InputBinding("Space", { light: "/Icons/1.1/Light/Space.svg", dark: "/Icons/1.1/Dark/Space.svg" },  InputListener.Keyboard)],
        ["AltRight", new InputBinding("AltRight", { light: "/Icons/1.1/Light/AltRight.svg", dark: "/Icons/1.1/Dark/AltRight.svg" },  InputListener.Keyboard)],
        ["ContextMenu", new InputBinding("ContextMenu", { light: "/Icons/1.1/Light/ContextMenu.svg", dark: "/Icons/1.1/Dark/ContextMenu.svg" },  InputListener.Keyboard)],
        ["ControlRight", new InputBinding("ControlRight", { light: "/Icons/1.1/Light/ControlRight.svg", dark: "/Icons/1.1/Dark/ControlRight.svg" },  InputListener.Keyboard)],
        ["ScrollLock", new InputBinding("ScrollLock", { light: "/Icons/1.1/Light/ScrollLock.svg", dark: "/Icons/1.1/Dark/ScrollLock.svg" },  InputListener.Keyboard)],
        ["Pause", new InputBinding("Pause", { light: "/Icons/1.1/Light/Pause.svg", dark: "/Icons/1.1/Dark/Pause.svg" },  InputListener.Keyboard)],
        ["Insert", new InputBinding("Insert", { light: "/Icons/1.1/Light/Insert.svg", dark: "/Icons/1.1/Dark/Insert.svg" },  InputListener.Keyboard)],
        ["Home", new InputBinding("Home", { light: "/Icons/1.1/Light/Home.svg", dark: "/Icons/1.1/Dark/Home.svg" },  InputListener.Keyboard)],
        ["PageUp", new InputBinding("PageUp", { light: "/Icons/1.1/Light/PageUp.svg", dark: "/Icons/1.1/Dark/PageUp.svg" },  InputListener.Keyboard)],
        ["Delete", new InputBinding("Delete", { light: "/Icons/1.1/Light/Delete.svg", dark: "/Icons/1.1/Dark/Delete.svg" },  InputListener.Keyboard)],
        ["End", new InputBinding("End", { light: "/Icons/1.1/Light/End.svg", dark: "/Icons/1.1/Dark/End.svg" },  InputListener.Keyboard)],
        ["PageDown", new InputBinding("PageDown", { light: "/Icons/1.1/Light/PageDown.svg", dark: "/Icons/1.1/Dark/PageDown.svg" },  InputListener.Keyboard)],
        ["ArrowUp", new InputBinding("ArrowUp", { light: "/Icons/1.1/Light/ArrowUp.svg", dark: "/Icons/1.1/Dark/ArrowUp.svg" },  InputListener.Keyboard)],
        ["ArrowLeft", new InputBinding("ArrowLeft", { light: "/Icons/1.1/Light/ArrowLeft.svg", dark: "/Icons/1.1/Dark/ArrowLeft.svg" },  InputListener.Keyboard)],
        ["ArrowDown", new InputBinding("ArrowDown", { light: "/Icons/1.1/Light/ArrowDown.svg", dark: "/Icons/1.1/Dark/ArrowDown.svg" },  InputListener.Keyboard)],
        ["ArrowRight", new InputBinding("ArrowRight", { light: "/Icons/1.1/Light/ArrowRight.svg", dark: "/Icons/1.1/Dark/ArrowRight.svg" },  InputListener.Keyboard)],
        ["NumLock", new InputBinding("NumLock", { light: "/Icons/1.1/Light/NumLock.svg", dark: "/Icons/1.1/Dark/NumLock.svg" },  InputListener.Keyboard)],
        ["NumpadDivide", new InputBinding("NumpadDivide", { light: "/Icons/1.1/Light/NumpadDivide.svg", dark: "/Icons/1.1/Dark/NumpadDivide.svg" },  InputListener.Keyboard)],
        ["NumpadMultiply", new InputBinding("NumpadMultiply", { light: "/Icons/1.1/Light/NumpadMultiply.svg", dark: "/Icons/1.1/Dark/NumpadMultiply.svg" },  InputListener.Keyboard)],
        ["NumpadSubtract", new InputBinding("NumpadSubtract", { light: "/Icons/1.1/Light/NumpadSubtract.svg", dark: "/Icons/1.1/Dark/NumpadSubtract.svg" },  InputListener.Keyboard)],
        ["Numpad7", new InputBinding("Numpad7", { light: "/Icons/1.1/Light/Numpad7.svg", dark: "/Icons/1.1/Dark/Numpad7.svg" },  InputListener.Keyboard)],
        ["Numpad8", new InputBinding("Numpad8", { light: "/Icons/1.1/Light/Numpad8.svg", dark: "/Icons/1.1/Dark/Numpad8.svg" },  InputListener.Keyboard)],
        ["Numpad9", new InputBinding("Numpad9", { light: "/Icons/1.1/Light/Numpad9.svg", dark: "/Icons/1.1/Dark/Numpad9.svg" },  InputListener.Keyboard)],
        ["NumpadAdd", new InputBinding("NumpadAdd", { light: "/Icons/1.1/Light/NumpadAdd.svg", dark: "/Icons/1.1/Dark/NumpadAdd.svg" },  InputListener.Keyboard)],
        ["Numpad4", new InputBinding("Numpad4", { light: "/Icons/1.1/Light/Numpad4.svg", dark: "/Icons/1.1/Dark/Numpad4.svg" },  InputListener.Keyboard)],
        ["Numpad5", new InputBinding("Numpad5", { light: "/Icons/1.1/Light/Numpad5.svg", dark: "/Icons/1.1/Dark/Numpad5.svg" },  InputListener.Keyboard)],
        ["Numpad6", new InputBinding("Numpad6", { light: "/Icons/1.1/Light/Numpad6.svg", dark: "/Icons/1.1/Dark/Numpad6.svg" },  InputListener.Keyboard)],
        ["Numpad1", new InputBinding("Numpad1", { light: "/Icons/1.1/Light/Numpad1.svg", dark: "/Icons/1.1/Dark/Numpad1.svg" },  InputListener.Keyboard)],
        ["Numpad2", new InputBinding("Numpad2", { light: "/Icons/1.1/Light/Numpad2.svg", dark: "/Icons/1.1/Dark/Numpad2.svg" },  InputListener.Keyboard)],
        ["Numpad3", new InputBinding("Numpad3", { light: "/Icons/1.1/Light/Numpad3.svg", dark: "/Icons/1.1/Dark/Numpad3.svg" },  InputListener.Keyboard)],
        ["Numpad0", new InputBinding("Numpad0", { light: "/Icons/1.1/Light/Numpad0.svg", dark: "/Icons/1.1/Dark/Numpad0.svg" },  InputListener.Keyboard)],
        ["NumpadDecimal", new InputBinding("NumpadDecimal", { light: "/Icons/1.1/Light/NumpadDecimal.svg", dark: "/Icons/1.1/Dark/NumpadDecimal.svg" },  InputListener.Keyboard)],
        [InputBinding.MouseWheelUp, new InputBinding(InputBinding.MouseWheelUp, { light: "/Icons/1.1/Light/MouseWheelUp.svg", dark: "/Icons/1.1/Dark/MouseWheelUp.svg" },  InputListener.Wheel)],
        [InputBinding.MouseWheelDown, new InputBinding(InputBinding.MouseWheelDown, { light: "/Icons/1.1/Light/MouseWheelDown.svg", dark: "/Icons/1.1/Dark/MouseWheelDown.svg" },  InputListener.Wheel)],
    ]);

    public getLocalUserKeybinds(): IActionMap<InputBinding> {
        const keybindJson = localStorage.getItem("keybinds");
        if (keybindJson) {
            const keybinds = JSON.parse(keybindJson);
            return keybinds as IActionMap<InputBinding>; // TODO build adapter
        } else {
            return KeyBindSystem.defaults;
        }
    }

    public getStoredUserKeybinds(): IActionMap<InputBinding> {
        return {} as IActionMap<InputBinding>;
    }

    public static readonly defaults: IActionMap<InputBinding> = {
        MoveForward: this.bindings.get("KeyW")!,
        MoveBackward: this.bindings.get("KeyS")!,
        MoveLeft: this.bindings.get("KeyA")!,
        MoveRight: this.bindings.get("KeyD")!,
        Jump: this.bindings.get("Space")!,
        Crouch: this.bindings.get("KeyC")!,
        Prone: this.bindings.get("ControlLeft")!,
        Sprint: this.bindings.get("ShiftLeft")!,
        Interact: this.bindings.get("KeyF")!,
        Menu: this.bindings.get("Escape")!,
        Fire: this.bindings.get("0")!,
        Aim: this.bindings.get("1")!,
        Reload: this.bindings.get("KeyR")!,
        NextWeapon: this.bindings.get(InputBinding.MouseWheelUp)!,
        PrevWeapon: this.bindings.get(InputBinding.MouseWheelDown)!,
        LethalEquipment: this.bindings.get("KeyG")!,
        TacticalEquipment: this.bindings.get("KeyQ")!
    }

    public static getDefaultBinding(action: keyof IActionMap<InputBinding>): InputBinding {
        return KeyBindSystem.defaults[action];
    }
}